name: absence_app
description: Sistema de Controle de Faltas AcadÃªmicas
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_app_check: ^0.3.1+4
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  http: ^1.2.0
  http_parser: ^4.0.2
  intl: ^0.18.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^10.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

